[tool.black]
line-length = 100
exclude = ['migrations']

[tool.djlint]
profile = 'django'
use_gitignore = true
blank_line_before_tag = 'block'
blank_line_after_tag = 'load,extends,include,endblock'
format_attribute_template_tags = true

[tool.flake8]
ignore = ['W503']
max-line-length = 100

[tool.isort]
profile = 'black'
line_length = 100
lines_after_imports = 2
skip_gitignore = true
extend_skip = ['migrations']
